name: Coverity Scan

# We only want to test official release code, not every pull request.
on:
  push:
    branches:
    - main

permissions: read-all

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: vapier/coverity-scan-action@v1
      with:
        project: Template-Repo
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        working-directory: 'cpp_source'
